@echo off
echo Compilation started...
echo g++ -g -std=c++17 -I../core t_main.cpp ../core/c_gate.cpp -o t_main.exe
g++ -g -std=c++17 -I../core t_main.cpp ../core/c_gate.cpp -o t_main.exe
echo Compilation ended...
